#!/usr/bin/env python3
"""Build the static-browser Knowledge Base bundle from knowledge/kb.json.

LabFlow can run from file://, so runtime code cannot rely on fetch(). The JSON file
is the human/source-controlled representation; this generated bundle exposes the
same payload synchronously as window.LabFlowKnowledgeBundle.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "knowledge" / "kb.json"
TARGET = ROOT / "assets" / "js" / "knowledge" / "kb-bundle.js"


def main() -> None:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or not isinstance(payload.get("entries"), list):
        raise SystemExit("knowledge/kb.json must contain an entries array")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    TARGET.write_text(
        "/* Generated by tools/build_knowledge_bundle.py. Do not edit directly. */\n"
        "window.LabFlowKnowledgeBundle=" + encoded + ";\n",
        encoding="utf-8",
    )
    print(f"Built {TARGET.relative_to(ROOT)} · {len(payload['entries'])} entries")


if __name__ == "__main__":
    main()
