#!/usr/bin/env python3
"""Compile canonical Markdown documentation into a file://-safe browser bundle."""
from __future__ import annotations

from hashlib import sha256
from pathlib import Path
import base64
import json
import re

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
TARGET = ROOT / "assets/js/pages/docs-bundle.js"

SECTION_ORDER = {
    "Researcher guide": 0,
    "Operating model": 1,
    "Scientific data": 2,
    "AI and Actions": 3,
    "Export and NOMAD": 4,
    "Engineering reference": 5,
}


def frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        key, sep, value = line.partition(":")
        if sep:
            meta[key.strip()] = value.strip()
    return meta, text[end + 5 :]


def section_for(relative: Path) -> str:
    path = relative.as_posix()
    name = relative.name
    if path.startswith("guides/"):
        return "Researcher guide"
    if path.startswith("data/") or name in {"EXPERIMENT_MODEL.md"}:
        return "Scientific data"
    if name in {"AI.md"} or name in {"ACTIONS.md", "AI_PROVIDERS.md", "TOOLS.md"}:
        return "AI and Actions"
    if name in {"NOMAD.md", "IMPORT_EXPORT.md"}:
        return "Export and NOMAD"
    if name in {"WORKFLOW.md", "ARCHITECTURE.md"}:
        return "Operating model"
    return "Engineering reference"


def first_paragraph(body: str) -> str:
    blocks = re.split(r"\n\s*\n", body)
    for block in blocks:
        clean = block.strip()
        if not clean or clean.startswith(("#", "```", "|", ">", "- ")):
            continue
        return re.sub(r"[*_`\[\]]", "", clean).replace("\n", " ")[:180]
    return "Canonical LabFlow documentation."


def slug_for(relative: Path) -> str:
    return relative.with_suffix("").as_posix().lower().replace("_", "-").replace("/", "--")


def main() -> None:
    paths = sorted(
        path for path in DOCS.rglob("*.md")
        if "superpowers" not in path.parts and path.name != "AUDIT_REPORT.md"
    )
    docs = []
    digest = sha256()
    for path in paths:
        relative = path.relative_to(DOCS)
        source = path.read_text(encoding="utf-8")
        meta, body = frontmatter(source)
        heading = re.search(r"^#\s+(.+)$", body, re.M)
        title = meta.get("title") or (heading.group(1).strip() if heading else relative.stem.replace("_", " ").title())
        section = meta.get("section") or section_for(relative)
        outline = [
            {"level": len(match.group(1)), "title": re.sub(r"[*_`]", "", match.group(2)).strip()}
            for match in re.finditer(r"^(#{1,4})\s+(.+)$", body, re.M)
        ]
        words = len(re.findall(r"\b[\w'-]+\b", body))
        order = int(meta.get("order", "999"))
        record = {
            "slug": slug_for(relative),
            "path": "docs/" + relative.as_posix(),
            "title": title,
            "section": section,
            "summary": meta.get("summary") or first_paragraph(body),
            "order": order,
            "words": words,
            "outline": outline,
            "markdown": body.strip() + "\n",
        }
        docs.append(record)
        digest.update(relative.as_posix().encode())
        digest.update(source.encode())

    docs.sort(key=lambda item: (SECTION_ORDER.get(item["section"], 99), item["order"], item["title"].lower()))
    payload = json.dumps({"digest": digest.hexdigest(), "documents": docs}, ensure_ascii=False, separators=(",", ":"))
    encoded = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    output = (
        "// Generated by tools/build_docs_bundle.py from docs/**/*.md · sha256:" + digest.hexdigest() + "\n"
        "(function(){'use strict';const LF=window.LabFlow=window.LabFlow||{},raw=atob('" + encoded + "'),bytes=Uint8Array.from(raw,function(c){return c.charCodeAt(0);});LF.DocsBundle=JSON.parse(new TextDecoder().decode(bytes));}());\n"
    )
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(output, encoding="utf-8")
    print(f"Documentation bundle: {TARGET.relative_to(ROOT)} ({len(docs)} Markdown files, {len(output)} chars)")


if __name__ == "__main__":
    main()
