#!/usr/bin/env python3
"""Build checked-in frontend bundles used by the static GitHub Pages POC.

The readable source files remain canonical. The generated bundles reduce the
number of network requests without introducing a runtime build requirement.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CSS_SOURCES = [
    "ui/foundations/tokens.css",
    "ui/themes/theme-base.css",
    "ui/themes/theme-dark.css",
    "ui/themes/theme-light.css",
    "ui/themes/palettes.css",
    "ui/foundations/base.css",
    "ui/layout/shell.css",
    "ui/components/core.css",
    "ui/components/scientific.css",
    "ui/components/knowledge-tools.css",
    "ui/foundations/utilities.css",
    "ui/layout/responsive.css",
]

RUNTIME_SOURCES = [
    "assets/js/icons.js",
    "assets/js/settings-bundle.js",
    "assets/js/data.js",
    "assets/js/pipeline-bundle.js",
    "assets/js/exporters.js",
    "assets/js/state.js",
]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8").strip()


def documentation_index() -> list[dict[str, str]]:
    source = read("assets/js/docs-bundle.js")
    marker = "window.LabFlowDocs ="
    position = source.find(marker)
    if position < 0:
        raise RuntimeError("Unexpected docs-bundle.js format")
    payload = source[position + len(marker):].strip().removesuffix(";")
    documents = json.loads(payload)
    keys = ("id", "title", "path", "updated", "status", "description")
    return [{key: document.get(key, "") for key in keys} for document in documents]


def build_css() -> None:
    parts = ["/* Generated by tools/build_frontend_bundles.py. Edit source files, not this bundle. */"]
    for path in CSS_SOURCES:
        parts.extend((f"\n/* --- {path} --- */", read(path)))
    (ROOT / "ui/labflow.bundle.css").write_text("\n".join(parts) + "\n", encoding="utf-8")


def build_runtime() -> None:
    parts = ["/* Generated by tools/build_frontend_bundles.py. Edit source files, not this bundle. */"]
    for path in RUNTIME_SOURCES:
        parts.extend((f"\n/* --- {path} --- */", read(path), ";"))
    metadata = json.dumps(documentation_index(), ensure_ascii=False, separators=(",", ":"))
    parts.extend(("\n/* Lightweight documentation metadata for global search. */", f"window.LabFlowDocs={metadata};"))
    (ROOT / "assets/js/runtime.js").write_text("\n".join(parts) + "\n", encoding="utf-8")


def main() -> None:
    build_css()
    build_runtime()
    print("Wrote ui/labflow.bundle.css and assets/js/runtime.js")


if __name__ == "__main__":
    main()
