#!/usr/bin/env python3
"""Generate a human-readable Action runtime matrix from canonical action.json files."""
from __future__ import annotations

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
ACTIONS = ROOT / "actions"
TARGET = ROOT / "docs" / "reference" / "ACTION_RUNTIME_MATRIX.md"


def text(value, default="—"):
    if value is None or value == "":
        return default
    return str(value)


def retry_value(step):
    semantic = int(step.get("max_retries", 0) or 0)
    return f"{semantic} semantic"


def main():
    rows = []
    details = []
    for path in sorted(ACTIONS.glob("*/action.json")):
        action = json.loads(path.read_text(encoding="utf-8"))
        ai_steps = [step for step in action.get("steps", []) if step.get("type") == "AI"]
        if not ai_steps:
            rows.append((action["id"], action.get("role", ""), action.get("type", ""), "—", "—", "—", "—", "—"))
            continue
        for step in ai_steps:
            rows.append((
                action["id"] + (f" / {step.get('id')}" if len(ai_steps) > 1 else ""),
                action.get("role", ""),
                action.get("type", ""),
                text(step.get("max_input_tokens")),
                text(step.get("target_output_tokens")),
                text(step.get("max_output_tokens")),
                retry_value(step),
                (f"{int(step.get('deadline_ms', 0))/1000:g} s" if step.get("deadline_ms") else "—"),
            ))
        details.append((action, ai_steps))

    lines = [
        "---",
        "title: Action runtime matrix",
        "section: AI and Actions",
        "summary: Generated reference for current Action input/output token budgets, retry policy and inference deadlines.",
        "order: 40",
        "---",
        "",
        "# Action runtime matrix",
        "",
        "> **Generated reference.** Do not edit this file by hand. Run `python tools/build_action_reference.py` after changing any `actions/*/action.json` contract.",
        "",
        "The table below describes **LabFlow operational budgets**, not the theoretical limits of a provider model. A model may support a much larger context or output window; each Action still works inside its own smaller contract.",
        "",
        "| Action / AI step | Role | Type | Max input | Target output | Output ceiling | Retries | Inference deadline |",
        "|---|---|---|---:|---:|---:|---|---:|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(x).replace("|", "\\|") for x in row) + " |")

    lines += [
        "",
        "## How to read the table",
        "",
        "- **Max input** is the Action-level prompt/context ceiling after deterministic Context Pack construction and compaction.",
        "- **Target output** is the normal requested completion size for that work unit.",
        "- **Output ceiling** is the Action hard ceiling before model/provider/user clamping.",
        "- **Retries** are semantic Action validation/rewrite retries only. Provider rate-limit responses are never retried automatically by the transport.",
        "- **Inference deadline** starts when the HTTP request starts. LabFlow does not add provider pacing before the request.",
        "",
        "## Important special cases",
        "",
        "- `analysis.enrich` is automatic, small and non-blocking. It has no Action retry; deterministic import remains valid if enrichment fails.",
        "- `design.infer` and `design.infer-batch` use zero automatic retries. In a multi-experiment Suggest-all run, the first provider throttle stops the sequence and leaves untouched experiments pending.",
        "- Z.AI `glm-4.7-flash` is never replaced automatically. A provider 429/`1305` is surfaced once with `Retry-After` when available and creates no local cooldown.",
        "- Report/Paper Actions split long writing into bounded work units. The table describes one AI work unit, not a promise that the entire document is generated in one provider call.",
        "",
        "See [AI runtime and limits](../guides/AI_TOKENS_AND_RATE_LIMITS.md), [AI provider specification](../specs/AI_PROVIDERS.md), and [Action specification](../specs/ACTIONS.md).",
        "",
    ]
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Action reference: {TARGET.relative_to(ROOT)} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
