#!/usr/bin/env python3
"""Generate the file://-safe inline UI Kit module from ui-kit.html.

The standalone HTML remains the human-editable visual ground truth. The app shell
cannot iframe it under file:// because sibling local documents have opaque origins
in Chromium, so this script mirrors only the catalog <main> body into a JS template.
"""
from __future__ import annotations

from hashlib import sha256
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ui-kit.html"
TARGET = ROOT / "assets/js/pages/ui-kit-inline.js"


def extract_main(source: str) -> str:
    opening = re.search(r'<main class="main-area">', source)
    if not opening:
        raise SystemExit("Could not find <main class=\"main-area\"> in ui-kit.html")
    depth = 1
    for tag in re.finditer(r'</?main\b[^>]*>', source[opening.end():], re.I):
        depth += -1 if tag.group(0).startswith('</') else 1
        if depth == 0:
            return source[opening.end():opening.end() + tag.start()].strip()
    raise SystemExit("Could not find the closing </main> for the UI Kit catalog")


def js_template_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    digest = sha256(source.encode("utf-8")).hexdigest()
    inner = js_template_escape(extract_main(source))
    output = f"""// Generated by tools/build_ui_kit_inline.py from ui-kit.html · sha256:{digest}\n(function () {{\n  'use strict';\n  const LF = window.LabFlow = window.LabFlow || {{}};\n  const TEMPLATE = `{inner}`;\n\n  function normalizeFilter(value) {{ return String(value || 'all').trim() || 'all'; }}\n  function normalizeQuery(value) {{ return String(value || '').trim().toLowerCase(); }}\n\n  function render() {{\n    return '<section class=\"ui-kit-inline-host\" aria-label=\"LabFlow UI Kit\">' + TEMPLATE + '</section>';\n  }}\n\n  function apply(state) {{\n    const root = document.querySelector('.ui-kit-inline-host');\n    if (!root) return 0;\n    const filter = normalizeFilter(state && state.uiKitFilter);\n    const query = normalizeQuery(state && state.uiKitQuery);\n    let visible = 0;\n    root.querySelectorAll('[data-ui-kit-group]').forEach(function (section) {{\n      const matchesFamily = filter === 'all' || section.dataset.uiKitGroup === filter;\n      const matchesText = !query || section.textContent.toLowerCase().includes(query);\n      section.hidden = !(matchesFamily && matchesText);\n      if (!section.hidden) visible += 1;\n    }});\n    const count = document.getElementById('uiKitGlobalCount');\n    if (count) count.textContent = visible + ' pattern' + (visible === 1 ? '' : 's');\n    return visible;\n  }}\n\n  LF.UIKitInline = {{render:render, apply:apply}};\n}}());\n"""
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(output, encoding="utf-8")
    print(f"UI Kit inline bundle: {TARGET.relative_to(ROOT)} ({len(output)} chars)")


if __name__ == "__main__":
    main()
