#!/usr/bin/env python3
"""Compile prompts/**/*.md into a file://-safe browser bundle.

Markdown files remain the source of truth. This helper has no runtime role.

Action definitions and their prompts live under actions/** and are compiled by tools/build_action_registry.py. This script compiles only shared policies and system utilities.
"""
from __future__ import annotations
import json
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / 'prompts'
OUT = ROOT / 'assets/js/ai/prompt-bundle.js'


def parse_frontmatter(text: str):
    meta = {}
    body = text
    if text.startswith('---\n'):
        end = text.find('\n---\n', 4)
        if end >= 0:
            raw = text[4:end]
            body = text[end + 5:]
            for line in raw.splitlines():
                if ':' not in line:
                    continue
                k, v = line.split(':', 1)
                v = v.strip()
                if v.lower() in ('true', 'false'):
                    value = v.lower() == 'true'
                else:
                    value = v
                meta[k.strip()] = value
    return meta, body.strip()


def extract_named_json(markdown: str, name: str):
    m = re.search(r'```json\s+' + re.escape(name) + r'\s*\n(.*?)\n```', markdown, re.S | re.I)
    if not m:
        return None
    return json.loads(m.group(1))

def extract_rules(markdown: str):
    return extract_named_json(markdown, 'labflow-rules')

def extract_ground_truth(markdown: str):
    return extract_named_json(markdown, 'labflow-ground-truth')


entries = {}
source_parts = []
for p in sorted(PROMPTS.rglob('*.md')):
    if p.name == 'README.md':
        continue
    text = p.read_text(encoding='utf-8')
    source_parts.append(p.relative_to(ROOT).as_posix() + '\0' + text)
    meta, body = parse_frontmatter(text)
    pid = meta.get('id')
    if not pid:
        raise SystemExit(f'Missing id in {p}')
    if pid in entries:
        raise SystemExit(f'Duplicate prompt id {pid!r} in {p} and {entries[pid]["path"]}')
    entries[pid] = {
        **meta,
        'path': p.relative_to(ROOT).as_posix(),
        'markdown': body,
    }
    rules = extract_rules(body)
    if rules is not None:
        entries[pid]['rules'] = rules
    ground_truth = extract_ground_truth(body)
    if ground_truth is not None:
        entries[pid]['ground_truth'] = ground_truth

payload = json.dumps(entries, ensure_ascii=False, indent=2)
source_digest = hashlib.sha256('\n'.join(source_parts).encode('utf-8')).hexdigest()
js = f"""// GENERATED by tools/build_prompt_bundle.py. Edit prompts/**/*.md, not this file.
// SOURCE_SHA256: {source_digest}
(function () {{
  'use strict';
  const LF = window.LabFlow = window.LabFlow || {{}};
  const Log = LF.Logger ? LF.Logger.scope('prompts') : null;
  const ENTRIES = {payload};

  function entry(id) {{
    const e = ENTRIES[id] || null;
    if (Log) Log.trace('entry', {{id:id, found:!!e}});
    return e;
  }}
  function defaults() {{
    const out = {{}};
    Object.keys(ENTRIES).forEach(function(id) {{ out[id] = ENTRIES[id].markdown; }});
    return out;
  }}
  function extractRules(markdown) {{
    const m = String(markdown || '').match(/```json\\s+labflow-rules\\s*\\n([\\s\\S]*?)\\n```/i);
    if (!m) {{
      if (Log) Log.warn('rules.block-missing');
      return null;
    }}
    try {{
      const parsed = JSON.parse(m[1]);
      if (Log) Log.debug('rules.parsed', {{sections:Object.keys(parsed || {{}})}});
      return parsed;
    }} catch (err) {{
      if (Log) Log.error('rules.parse-failed', {{error:err}});
      return null;
    }}
  }}
  function promptText(id) {{
    const text = ENTRIES[id] ? ENTRIES[id].markdown : '';
    if (Log) Log.trace('prompt.resolve', {{id:id, chars:String(text || '').length}});
    return text;
  }}
  let rulesCacheText = null;
  let rulesCacheValue = null;
  function deepMerge(a,b) {{
    const out = Object.assign({{}}, a || {{}});
    Object.keys(b || {{}}).forEach(function(k) {{
      if (b[k] && typeof b[k] === 'object' && !Array.isArray(b[k]) && out[k] && typeof out[k] === 'object' && !Array.isArray(out[k])) out[k] = deepMerge(out[k], b[k]);
      else out[k] = b[k];
    }});
    return out;
  }}
  function extractGroundTruth(markdown) {{
    const m = String(markdown || '').match(/```json\\s+labflow-ground-truth\\s*\\n([\\s\\S]*?)\\n```/i);
    if (!m) return null;
    try {{ return JSON.parse(m[1]); }} catch (err) {{ if(Log)Log.error('ground-truth.parse-failed',{{error:err}}); return null; }}
  }}
  function effectiveRules() {{
    const gtMarkdown = promptText('policy.data-ground-truth');
    const repairMarkdown = promptText('policy.data-format-repair');
    const cacheKey = gtMarkdown + '\\n---REPAIR---\\n' + repairMarkdown;
    if (rulesCacheValue && cacheKey === rulesCacheText) return rulesCacheValue;
    const ground = extractGroundTruth(gtMarkdown) || (ENTRIES['policy.data-ground-truth'] && ENTRIES['policy.data-ground-truth'].ground_truth) || {{}};
    const repair = extractRules(repairMarkdown) || (ENTRIES['policy.data-format-repair'] && ENTRIES['policy.data-format-repair'].rules) || {{}};
    rulesCacheText = cacheKey;
    rulesCacheValue = deepMerge(ground, repair);
    if (Log) Log.info('rules.cached', {{source:'ground-truth+repair-policy', sections:Object.keys(rulesCacheValue || {{}})}});
    return rulesCacheValue;
  }}
  function policyIds() {{ return Object.keys(ENTRIES).filter(function(id) {{ return ENTRIES[id].kind === 'policy'; }}); }}

  LF.PromptRegistry = {{
    entries:ENTRIES,
    entry:entry,
    promptText:promptText,
    effectiveRules:effectiveRules,
    extractRules:extractRules,
    extractGroundTruth:extractGroundTruth,
    policyIds:policyIds
  }};
  LF.PromptDefaults = defaults();
  if (Log) Log.info('registry.ready', {{entries:Object.keys(ENTRIES).length, policies:policyIds().length}});
}}());
"""
OUT.write_text(js, encoding='utf-8')
print(f'Wrote {OUT.relative_to(ROOT)} with {len(entries)} Markdown prompts/policies')
