#!/usr/bin/env python3
"""Generate the browser-ready static Pipeline bundle from canonical YAML + step HTML.

LabFlow is deployed as plain static files (for example on GitHub Pages). Browsers
cannot fetch local files from file://, so the POC ships a generated JavaScript
bundle containing Pipeline metadata and step HTML fragments. The canonical,
human-edited sources remain pipelines/*/pipeline.yaml and steps/*/index.html.

This tool has no third-party dependencies.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets" / "pipeline-bundle.js"


def scalar(value: str):
    raw = value.strip().strip("'\"")
    if raw.lower() in {"true", "false"}:
        return raw.lower() == "true"
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    if re.fullmatch(r"-?\d+\.\d+", raw):
        return float(raw)
    return raw


def parse_pipeline(path: Path) -> dict:
    data: dict = {"steps": []}
    current = None
    in_steps = False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = re.sub(r"\s+#.*$", "", raw)
        if not line.strip():
            continue
        if re.fullmatch(r"steps:\s*", line):
            in_steps = True
            continue
        item = re.match(r"^\s*-\s+([\w-]+):\s*(.+)$", line)
        if in_steps and item:
            current = {item.group(1): scalar(item.group(2))}
            data["steps"].append(current)
            continue
        nested = re.match(r"^\s+([\w-]+):\s*(.+)$", line)
        if in_steps and current is not None and nested:
            current[nested.group(1)] = scalar(nested.group(2))
            continue
        root = re.match(r"^([\w-]+):\s*(.+)$", line)
        if root:
            data[root.group(1)] = scalar(root.group(2))
    return data


def build_bundle() -> dict:
    bundle: dict[str, dict] = {}
    for yaml_path in sorted((ROOT / "pipelines").glob("*/pipeline.yaml")):
        pipeline = parse_pipeline(yaml_path)
        pipeline_id = str(pipeline.get("id") or yaml_path.parent.name)
        pipeline["base"] = f"pipelines/{yaml_path.parent.name}/"
        for step in pipeline.get("steps", []):
            html_rel = step.get("html")
            if not html_rel:
                raise SystemExit(f"{yaml_path}: step {step.get('id', '?')} has no html asset")
            html_path = yaml_path.parent / str(html_rel)
            if not html_path.is_file():
                raise SystemExit(f"{yaml_path}: missing step HTML {html_rel}")
            step["htmlContent"] = html_path.read_text(encoding="utf-8")
        bundle[pipeline_id] = pipeline
    return bundle


def render(bundle: dict) -> str:
    payload = json.dumps(bundle, ensure_ascii=False, indent=2)
    return f'''/**
 * LabFlow Static Pipeline Bundle — GENERATED FILE
 * ================================================
 *
 * DO NOT EDIT THIS FILE BY HAND.
 *
 * Canonical sources:
 *   - each pipelines/<id>/pipeline.yaml
 *   - each pipelines/<id>/steps/<step>/index.html
 *
 * Why this generated file exists:
 * LabFlow is a zero-backend static POC intended for GitHub Pages. Keeping the
 * browser runtime free of fetch() calls also lets the shell open from file://
 * without CORS failures. YAML remains the human-readable authoring format;
 * this bundle is only its browser-ready, validator-checked representation.
 *
 * Refresh after changing a Pipeline:
 *   python3 tools/sync_pipeline_bundle.py
 *
 * Validate without modifying files:
 *   python3 tools/sync_pipeline_bundle.py --check
 */
(() => {{
  'use strict';
  window.LabFlowPipelineBundle = Object.freeze({payload});
}})();
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated bundle is stale")
    args = parser.parse_args()
    expected = render(build_bundle())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("Pipeline bundle is stale. Run: python3 tools/sync_pipeline_bundle.py", file=sys.stderr)
            return 1
        print("Pipeline bundle is synchronized with YAML and step HTML.")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
