'use strict';
require('../../assets/js/core.js');
require('../../assets/js/cabinet/cabinet.js');
module.exports=function(t,LF){
 t['Cabinet snapshot is detached and later Cabinet edits do not mutate Design copy']=function(){LF.Cabinet.reset({items:[]});const item=LF.Cabinet.create('solution',{name:'Ink A',role:'absorber',solutes:'FAI'}),exp={design:{solutions:[],devices:[{id:'d1',solutionIds:[],stack:[],process:{}}]}};LF.Cabinet.applyToDesign(exp,'d1',item.id);const sol=exp.design.solutions[0];LF.Cabinet.update(item.id,{solutes:'FAI, PbI2'});if(sol.solutes!=='FAI')throw new Error('Design snapshot mutated after Cabinet edit');if(!sol.cabinetRef||sol.cabinetRef.cabinetId!==item.id)throw new Error('Cabinet provenance missing');};
 t['Cabinet process protocol snapshots into selected Design experiment']=function(){LF.Cabinet.reset({items:[]});const p=LF.Cabinet.create('protocol',{name:'Spin',coating:'spin coating',atmosphere:'N2'}),exp={design:{solutions:[],devices:[{id:'d1',solutionIds:[],stack:[],process:{coating:'',annealing:'',atmosphere:'',notes:''}}]}};LF.Cabinet.applyToDesign(exp,'d1',p.id);if(exp.design.devices[0].process.coating!=='spin coating'||exp.design.devices[0].process.atmosphere!=='N2')throw new Error('Protocol not applied');if(!exp.design.devices[0].processSourceRef)throw new Error('Protocol source ref missing');};
 t['Cabinet solution use normalizes incomplete Design arrays and preserves solvent chemistry']=function(){LF.Cabinet.reset({items:[]});const item=LF.Cabinet.create('solution',{name:'Ink B',role:'absorber precursor',solutes:'CsI + PbI2',solvents:'DMF + DMSO'}),exp={design:{devices:[{id:'d2'}]}};const out=LF.Cabinet.applyToDesign(exp,'d2',item.id);if(out.changed<2)throw new Error('Cabinet solution should be created and linked');if(exp.design.solutions[0].solvents!=='DMF + DMSO'||exp.design.solutions[0].solutes!=='CsI + PbI2')throw new Error('Cabinet chemistry not preserved');if(!exp.design.devices[0].solutionIds.includes(exp.design.solutions[0].id))throw new Error('Cabinet solution not linked');};
 t['Cabinet rejects name-only or role-only solution resources before Design mutation']=function(){LF.Cabinet.reset({items:[]});const item=LF.Cabinet.create('solution',{name:'Placeholder',role:'absorber precursor'}),exp={design:{solutions:[],devices:[{id:'d3'}]}};let threw=false;try{LF.Cabinet.applyToDesign(exp,'d3',item.id);}catch(err){threw=/solute or solvent/i.test(String(err.message));}if(!threw)throw new Error('Incomplete Cabinet solution must be rejected');if(exp.design.solutions.length)throw new Error('Rejected Cabinet solution mutated Design');};
 t['Saving an incomplete Design solution to Cabinet is blocked']=function(){LF.Cabinet.reset({items:[]});const exp={design:{solutions:[{id:'s-bad',name:'Placeholder',role:'absorber precursor'}],devices:[]}};let threw=false;try{LF.Cabinet.saveDesignSolution(exp,'s-bad');}catch(err){threw=/solute or solvent/i.test(String(err.message));}if(!threw)throw new Error('Incomplete Design solution should not enter Cabinet');};

 t['Incomplete Cabinet solutions are excluded from AI context and proposal matching']=function(){LF.Cabinet.reset({items:[]});const bad=LF.Cabinet.create('solution',{name:'Same name',role:'absorber precursor'}),good=LF.Cabinet.create('solution',{name:'Good ink',role:'absorber precursor',solutes:'FAI',solvents:'DMF'});const compact=LF.Cabinet.compactForAI('solution',8);if(compact.some(function(x){return x.id===bad.id;}))throw new Error('Incomplete solution leaked into AI context');if(!compact.some(function(x){return x.id===good.id;}))throw new Error('Complete solution missing from AI context');const matches=LF.Cabinet.matchProposal({solutions:[{name:'Same name',role:'absorber precursor',solutes:'FAI',solvents:'DMF'}],devices:[]});if(matches.some(function(x){return x.cabinetId===bad.id;}))throw new Error('Incomplete Cabinet item matched a Design proposal');};

};
