'use strict';
require('../../assets/js/logger.js');
require('../../assets/js/core.js');
require('../../assets/js/experiment/data-model.js');
require('../../assets/js/experiment/design-model.js');
require('../../assets/js/data/parser.js');
require('../../assets/js/experiment/canonical-store.js');
require('../../assets/js/data/analysis.js');
require('../../assets/js/data/analysis-summary.js');
require('../../assets/js/ai/prompt-bundle.js');
require('../../assets/js/ai/action-registry.js');
require('../../assets/js/page-context.js');
require('../../assets/js/ai/context.js');
function assert(a,b,l){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error((l||'assert')+': expected '+JSON.stringify(b)+' got '+JSON.stringify(a));}
module.exports=function(t,LF){
  function fake(){const e=LF.DataModel.create({sourceName:'demo.zip'});e.files=[{id:'fileA',path:'demo/A_JV.txt',name:'A_JV.txt',family:'jv'},{id:'fileB',path:'demo/B_JV.txt',name:'B_JV.txt',family:'jv'}];e.samples=[{id:'s1',name:'DEVICE A',rawName:'Device_A',group:'A',isRef:false,measurementIds:['m1']},{id:'s2',name:'DEVICE B',rawName:'Device_B',group:'B',isRef:false,measurementIds:['m2']}];e.measurements=[{id:'m1',path:'demo/A_JV.txt',sample:'DEVICE A',rawSample:'Device_A',group:'A',fw:{eff:20},rv:{eff:21},bestEff:21,qualityStatus:'valid',rankingEligible:true,flags:[]},{id:'m2',path:'demo/B_JV.txt',sample:'DEVICE B',rawSample:'Device_B',group:'B',fw:{eff:18},rv:{eff:19},bestEff:19,qualityStatus:'valid',rankingEligible:true,flags:[]}];e.findings=[{id:'fA',status:'open',severity:'warning',type:'naming',title:'Ambiguous A',target:'m1',measurementId:'m1',evidence:['Device_A alias']}];e.analysis={summary:{measurementCount:2},topNonRef:[],topRef:[],bestBySample:[]};e.design={devices:[{id:'devA',name:'A',sampleNames:['DEVICE A'],solutionIds:[],stack:[],process:{}}],solutions:[]};LF.CanonicalStore.build(e);return e;}
  function install(e,r){LF.DataModel.getExperiment=function(){return e;};LF.State={state:{experiment:e,ui:{route:r||'experiment-import',selectedMeasurementId:null,selectedDesignDeviceId:'devA'}}};LF.Storage=LF.Storage||{};LF.Storage.getAssistantSettings=function(){return{memoryTurns:4,memoryChars:3000,messageChars:1200,memoryEnabled:true,contextChars:12000};};}
  t['Canonical Store preserves aliases and evidence references']=function(){const e=fake(),s=LF.CanonicalStore.sample(e,'Device_A');assert(s.id,'s1','alias lookup');assert(LF.CanonicalStore.summary(e).relations>0,true,'relations');assert(LF.CanonicalStore.summary(e).evidence>0,true,'evidence');};
  t['assistant starts from one bounded deterministic chat context']=function(){const e=fake();install(e,'experiment-results');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,LF.ActionRegistry.steps(def)[0],{userText:'Explain DEVICE A'});assert(built.context.context_pack.profile,'chat','profile');assert(built.context.results.summary.measurementCount,2,'deterministic result summary included');assert(Array.isArray(built.context.measurements),true,'focused measurements included');assert(Object.prototype.hasOwnProperty.call(built.context,'tool_observations'),false,'no agent tool-planning payload');assert(JSON.stringify(built.context).length<12000,true,'bounded');};
  t['assistant ignores extraneous planner observations because context is deterministic']=function(){const e=fake();install(e,'experiment-results');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,LF.ActionRegistry.steps(def)[0],{userText:'Explain DEVICE A',agentObservations:[{tool:'results.get',result:{summary:{bestSample:'DEVICE A'}}}]});assert(Object.prototype.hasOwnProperty.call(built.context,'tools_used'),false,'no planner trace');assert(Object.prototype.hasOwnProperty.call(built.context,'tool_observations'),false,'no planner observations');assert(built.context.results.summary.measurementCount,2,'canonical context remains available');};
  t['ambiguity context contains only requested finding and linked records']=function(){const e=fake();install(e);e.datasetAnalysis={sourceRevision:0,ambiguousFindings:[{id:'fA',measurementId:'m1',title:'Ambiguous A',detail:'',target:'m1'}]};const def=LF.ActionRegistry.action('dataset.resolve-ambiguities'),step=LF.ActionRegistry.steps(def).find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{outputs:{collect:{finding_ids:['fA']}}});assert(built.context.findings.map(function(x){return x.id;}),['fA'],'finding scope');assert(built.context.measurements.map(function(x){return x.id;}),['m1'],'measurement scope');};
  t['Design context contains only selected experiment and current evidence']=function(){const e=fake();install(e,'experiment-design');e.designAnalysis={sourceRevision:0,samples:[{sample:e.samples[0],unknownFields:['stack']},{sample:e.samples[1],unknownFields:['stack']}],summary:{samples:2}};const def=LF.ActionRegistry.action('design.infer'),step=LF.ActionRegistry.steps(def).find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{params:{deviceId:'devA'}});assert(built.context.scope.sample_names,['DEVICE A'],'single experiment');assert(built.context.scope.unknown_fields,['solutions','stack','process'],'Design context stays limited to the three researcher-facing Design domains');assert(built.context.design_evidence_summary.raw_design_evidence_found,false,'absence of source Design evidence is explicit');assert(built.context.design_evidence_summary.inference_basis,'model_inference_only','model inference remains reviewable when source evidence is absent');};
  t['Data Contract is scoped to ambiguity repair only']=function(){const ambiguity=LF.ActionRegistry.action('dataset.resolve-ambiguities'),design=LF.ActionRegistry.action('design.infer'),results=LF.ActionRegistry.action('results.interpret');assert((ambiguity.policies||[]).includes('policy.data-ground-truth'),true,'ambiguity gets contract');assert((design.policies||[]).includes('policy.data-ground-truth'),false,'design uses context pack');assert((results.policies||[]).includes('policy.data-ground-truth'),false,'results uses context pack');};
  t['shared Experiment Brief is deterministic in downstream AI contexts']=function(){const e=fake();install(e,'experiment-results');e.experimentBrief=LF.ExperimentBrief.ensure(e);['results.interpret','results.compare','design.infer'].forEach(function(id){if(id==='results.compare')LF.State.state.ui.boxPlot={groups:['A','B'],metric:'eff',direction:'both',eligibleOnly:true};const def=LF.ActionRegistry.action(id),step=LF.ActionRegistry.steps(def).find(function(x){return x.type==='AI';}),opts=id==='design.infer'?{params:{deviceId:'devA'}}:id==='results.compare'?{params:{groups:['A','B'],metric:'eff',direction:'both',eligibleOnly:true}}:{},built=LF.ActionContext.build(def,step,opts);assert(built.context.experiment_brief.status,'deterministic',id+' brief');assert(!!built.context.experiment_brief.deterministic,true,id+' deterministic facts');});};
  t['scientific Actions use only declared current-context profiles']=function(){const e=fake();install(e,'experiment-results');['dataset.resolve-ambiguities','design.infer','results.interpret','results.compare'].forEach(function(id){const def=LF.ActionRegistry.action(id);assert(typeof (def.contract&&def.contract.context&&def.contract.context.profile),'string',id+' declares a current context profile');});};
  t['Settings runtime provider metadata is never included in Assistant semantic context']=function(){const e=fake();install(e,'settings');LF.Storage.getAiSettings=function(){return{provider:'llamacpp',model:'/models/secret-model.gguf',endpoint:'http://127.0.0.1:8080/v1',temperature:.7,thinkingMode:'off'};};const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,LF.ActionRegistry.steps(def)[0],{userText:'What should I check next?'}),json=JSON.stringify(built.context);assert(built.context.page_context.page,'Settings','current runtime surface is named');assert(built.context.page_context.data,undefined,'Settings data is excluded');assert(Object.prototype.hasOwnProperty.call(built.context,'question'),false,'user request is not duplicated inside the Context Pack');if(/secret-model|127\.0\.0\.1:8080|reasoning_format|response_format|thinkingMode/.test(json))throw new Error('runtime/provider metadata leaked into semantic context: '+json);};
  t['Logs runtime data is never included in Assistant semantic context']=function(){const e=fake();install(e,'logs');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,LF.ActionRegistry.steps(def)[0],{userText:'Explain the experiment'});assert(built.context.page_context.page,'Logs','logs surface named');assert(built.context.page_context.data,undefined,'diagnostic log contents excluded');};
  t['mechanical cleanup is pipeline work rather than a researcher Action']=function(){assert(LF.ActionRegistry.actions().length,5,'researcher Action catalog stays minimal');};
  return t;
};
