'use strict';
require('../../assets/js/logger.js');
require('../../assets/js/core.js');
require('../../assets/js/experiment/data-model.js');
require('../../assets/js/data/parser.js');
require('../../assets/js/experiment/canonical-store.js');
require('../../assets/js/data/analysis.js');
require('../../assets/js/data/analysis-summary.js');
require('../../assets/js/ai/prompt-bundle.js');
require('../../assets/js/ai/action-registry.js');
require('../../assets/js/ai/context.js');
function assert(a,b,l){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error((l||'assert')+': expected '+JSON.stringify(b)+' got '+JSON.stringify(a));}
module.exports=function(t,LF){
  function fake(){const e=LF.DataModel.create({sourceName:'demo.zip'});e.files=[{id:'fileA',path:'demo/A_JV.txt',name:'A_JV.txt',family:'jv'},{id:'fileB',path:'demo/B_JV.txt',name:'B_JV.txt',family:'jv'}];e.samples=[{id:'s1',name:'DEVICE A',rawName:'Device_A',group:'A',isRef:false,measurementIds:['m1']},{id:'s2',name:'DEVICE B',rawName:'Device_B',group:'B',isRef:false,measurementIds:['m2']}];e.measurements=[{id:'m1',path:'demo/A_JV.txt',sample:'DEVICE A',rawSample:'Device_A',group:'A',fw:{eff:20},rv:{eff:21},bestEff:21,qualityStatus:'valid',rankingEligible:true,flags:[]},{id:'m2',path:'demo/B_JV.txt',sample:'DEVICE B',rawSample:'Device_B',group:'B',fw:{eff:18},rv:{eff:19},bestEff:19,qualityStatus:'valid',rankingEligible:true,flags:[]}];e.findings=[{id:'fA',status:'open',severity:'warning',type:'naming',title:'Ambiguous A',target:'m1',measurementId:'m1',evidence:['Device_A alias']}];e.analysis={summary:{measurementCount:2},topNonRef:[],topRef:[],bestBySample:[]};e.design={devices:[{id:'devA',name:'A',sampleNames:['DEVICE A'],solutionIds:[],stack:[],process:{}}],solutions:[]};LF.CanonicalStore.build(e);return e;}
  function install(e,r){LF.DataModel.getExperiment=function(){return e;};LF.State={state:{experiment:e,ui:{route:r||'experiment-understand',selectedMeasurementId:null,selectedDesignDeviceId:'devA'}}};LF.Storage=LF.Storage||{};LF.Storage.getAssistantSettings=function(){return{memoryTurns:4,memoryChars:3000,messageChars:1200,memoryEnabled:true,contextChars:12000};};}
  t['Canonical Store preserves aliases and evidence references']=function(){const e=fake(),s=LF.CanonicalStore.sample(e,'Device_A');assert(s.id,'s1','alias lookup');assert(LF.CanonicalStore.summary(e).relations>0,true,'relations');assert(LF.CanonicalStore.summary(e).evidence>0,true,'evidence');};
  t['assistant starts from one bounded deterministic chat context']=function(){const e=fake();install(e,'experiment-results');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,def.steps[0],{userText:'Explain DEVICE A'});assert(built.context.context_pack.profile,'chat','profile');assert(built.context.results.summary.measurementCount,2,'deterministic result summary included');assert(Array.isArray(built.context.measurements),true,'focused measurements included');assert(Object.prototype.hasOwnProperty.call(built.context,'tool_observations'),false,'no agent tool-planning payload');assert(JSON.stringify(built.context).length<12000,true,'bounded');};
  t['assistant ignores legacy agent observations because the final context is deterministic']=function(){const e=fake();install(e,'experiment-results');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,def.steps[0],{userText:'Explain DEVICE A',agentObservations:[{tool:'results.get',arguments:{},result:{summary:{bestSample:'DEVICE A'}}}]});assert(Object.prototype.hasOwnProperty.call(built.context,'tools_used'),false,'no planner trace');assert(Object.prototype.hasOwnProperty.call(built.context,'tool_observations'),false,'no planner observations');assert(built.context.results.summary.measurementCount,2,'canonical context remains available');};
  t['ambiguity context contains only requested finding and linked records']=function(){const e=fake();install(e);e.datasetAnalysis={sourceRevision:0,ambiguousFindings:[{id:'fA',measurementId:'m1',title:'Ambiguous A',detail:'',target:'m1'}]};const def=LF.ActionRegistry.action('dataset.resolve-ambiguities'),step=def.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{outputs:{collect:{finding_ids:['fA']}}});assert(built.context.findings.map(function(x){return x.id;}),['fA'],'finding scope');assert(built.context.measurements.map(function(x){return x.id;}),['m1'],'measurement scope');};
  t['Design context contains only selected experiment and survives an empty Knowledge Base search']=function(){const e=fake();install(e,'experiment-design');e.designAnalysis={sourceRevision:0,samples:[{sample:e.samples[0],unknownFields:['stack']},{sample:e.samples[1],unknownFields:['stack']}],summary:{samples:2}};const previous=LF.KnowledgeBase;LF.KnowledgeBase={search:function(){return[];},context:function(){return[];}};try{const def=LF.ActionRegistry.action('design.infer'),step=def.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{params:{deviceId:'devA'}});assert(built.context.scope.sample_names,['DEVICE A'],'single experiment');assert(built.context.scope.unknown_fields,['stack','solutions'],'Design context stays limited to solution chemistry and device stack');assert(built.context.design_evidence_summary.knowledge_records_found,0,'empty search is explicit');assert(built.context.design_evidence_summary.knowledge_source,'model_inference_only','model inference remains available');assert(Object.prototype.hasOwnProperty.call(built.context,'knowledge_context'),false,'empty search adds no synthetic knowledge context');}finally{LF.KnowledgeBase=previous;}};
  t['Data Contract is scoped to ambiguity repair, not downstream prose']=function(){const ambiguity=LF.ActionRegistry.action('dataset.resolve-ambiguities'),design=LF.ActionRegistry.action('design.infer'),results=LF.ActionRegistry.action('results.interpret'),report=LF.ActionRegistry.action('report.generate');assert((ambiguity.policies||[]).includes('policy.data-ground-truth'),true,'ambiguity gets contract');assert((design.policies||[]).includes('policy.data-ground-truth'),false,'design uses context pack');assert((results.policies||[]).includes('policy.data-ground-truth'),false,'results uses context pack');assert((report.policies||[]).includes('policy.data-ground-truth'),false,'report uses context pack');};
  t['shared Experiment Brief is present in every AI context base']=function(){const e=fake();install(e,'experiment-results');e.experimentBrief=LF.ExperimentBrief.ensure(e);e.experimentBrief.ai={summary:'Shared scientific brief',inputSignature:LF.ExperimentBrief.signature(e),provenance:'ai_enrichment'};const resultDef=LF.ActionRegistry.action('results.interpret'),resultStep=resultDef.steps.find(function(x){return x.type==='AI';}),result=LF.ActionContext.build(resultDef,resultStep,{});const reportDef=LF.ActionRegistry.action('report.generate'),reportStep=reportDef.steps.find(function(x){return x.type==='AI';}),report=LF.ActionContext.build(reportDef,reportStep,{params:{document_kind:'lab'}});assert(result.context.experiment_brief.status,'ai_enriched','results brief');assert(report.context.experiment_brief.status,'ai_enriched','report brief');assert(report.context.experiment_brief.ai.summary,'Shared scientific brief','shared AI summary');};
  t['Report AI context carries deterministic report data instead of a prose-only summary']=function(){const e=fake();install(e,'experiment-report');const previous=LF.Report;LF.Report=Object.assign({},previous,{reportContextData:function(){return{dataState:{basis:'working_copy_modified'},metrics:{measurementCount:2},top10:[{cell:'DEVICE A',effRV:21}],statistics:{effRV:{median:20}},anomalies:[{title:'Check repeat'}],experimentalEvidence:{measurements:2}};}});try{const def=LF.ActionRegistry.action('report.generate'),step=def.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{params:{document_kind:'lab'}});assert(built.context.report_data.metrics.measurementCount,2,'deterministic metrics');assert(built.context.report_data.top10[0].cell,'DEVICE A','ranked result');assert(built.context.report_data.experimentalEvidence.measurements,2,'experimental evidence');}finally{LF.Report=previous;}};
  t['scientific Actions receive small optional Knowledge Base context']=function(){const e=fake();install(e,'experiment-results');const previous=LF.KnowledgeBase,record={id:'kb_ranked',collection:'science',kind:'material',name:'SnO2',summary:'ETL',tags:['SnO2'],data:{role:'ETL'},sources:[{title:'Paper',doi:'10.1000/kb'}],retrieval:{score:9,matched_terms:['sno2']}},seen=[];LF.KnowledgeBase={search:function(query,options){seen.push(options);return[record];},context:function(device,design,limit,query,options){seen.push(options);return[record];}};try{['analysis.enrich','design.infer','results.interpret','report.generate','report.improve'].forEach(function(id){seen.length=0;const def=LF.ActionRegistry.action(id),step=def.steps.find(function(x){return x.type==='AI';}),opts=id==='design.infer'?{params:{deviceId:'devA'}}:{params:{document_kind:'lab'}},built=LF.ActionContext.build(def,step,opts),knowledge=built.context.knowledge_context;assert(!!def.input.knowledge,true,id+' declares optional Knowledge Base retrieval');assert(def.input.knowledge.kinds.includes('concept'),true,id+' may use scientific concepts');assert(seen[0].collections,['science'],id+' restricts retrieval to scientific knowledge');assert(knowledge.records[0].id,'kb_ranked',id+' receives retrieved record');assert(knowledge.kind,'external_scientific_context_not_experiment_evidence',id+' labels KB context as external support');});}finally{LF.KnowledgeBase=previous;}};
  t['scientific Actions continue normally when Knowledge Base lookup fails']=function(){const e=fake();install(e,'experiment-results');e.designAnalysis={sourceRevision:0,samples:[{sample:e.samples[0],unknownFields:['stack']}],summary:{samples:1}};const previous=LF.KnowledgeBase;LF.KnowledgeBase={search:function(){throw new Error('lookup unavailable');},context:function(){throw new Error('lookup unavailable');}};try{['analysis.enrich','results.interpret','report.generate','report.improve'].forEach(function(id){const def=LF.ActionRegistry.action(id),step=def.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{params:{document_kind:'lab'}});assert(Object.prototype.hasOwnProperty.call(built.context,'knowledge_context'),false,id+' continues without KB context');});const design=LF.ActionRegistry.action('design.infer'),designStep=design.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(design,designStep,{params:{deviceId:'devA'}});assert(Object.prototype.hasOwnProperty.call(built.context,'knowledge_context'),false,'Design continues without KB context');assert(built.context.design_evidence_summary.knowledge_source,'model_inference_only','Design exposes the simple fallback mode');}finally{LF.KnowledgeBase=previous;}};
  t['Report context performs one Knowledge Base search and compaction can reuse it']=function(){const e=fake();install(e,'experiment-report');let calls=0;const previous=LF.KnowledgeBase,record={id:'kb_once',collection:'science',kind:'concept',name:'Recombination',summary:'Context',tags:['recombination'],data:{},sources:[]};LF.KnowledgeBase={status:function(){return{available:true};},search:function(){calls++;return[record];}};try{const def=LF.ActionRegistry.action('report.generate'),step=def.steps.find(function(x){return x.type==='AI';}),cache={};LF.ActionContext.build(def,step,{params:{document_kind:'lab'},retrievalCache:cache});LF.ActionContext.build(def,step,{params:{document_kind:'lab'},retrievalCache:cache,maxChars:3000});assert(calls,1,'same work-unit retrieval is reused during context compaction');}finally{LF.KnowledgeBase=previous;}};
  t['dataset Analyze is deterministic and promptless']=function(){const d=LF.ActionRegistry.action('dataset.analyze');assert(d.type,'DETERMINISTIC');assert(LF.ActionRegistry.prompt(d.id),'');};
  return t;
};
