'use strict';
require('../../assets/js/logger.js');
require('../../assets/js/core.js');
require('../../assets/js/experiment/data-model.js');
require('../../assets/js/data/parser.js');
require('../../assets/js/experiment/canonical-store.js');
require('../../assets/js/data/analysis.js');
require('../../assets/js/data/analysis-summary.js');
require('../../assets/js/ai/prompt-bundle.js');
require('../../assets/js/ai/action-registry.js');
require('../../assets/js/ai/context.js');
function assert(a,b,l){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error((l||'assert')+': expected '+JSON.stringify(b)+' got '+JSON.stringify(a));}
module.exports=function(t,LF){
  function fake(){const e=LF.DataModel.create({sourceName:'demo.zip'});e.files=[{id:'fileA',path:'demo/A_JV.txt',name:'A_JV.txt',family:'jv'},{id:'fileB',path:'demo/B_JV.txt',name:'B_JV.txt',family:'jv'}];e.samples=[{id:'s1',name:'DEVICE A',rawName:'Device_A',group:'A',isRef:false,measurementIds:['m1']},{id:'s2',name:'DEVICE B',rawName:'Device_B',group:'B',isRef:false,measurementIds:['m2']}];e.measurements=[{id:'m1',path:'demo/A_JV.txt',sample:'DEVICE A',rawSample:'Device_A',group:'A',fw:{eff:20},rv:{eff:21},bestEff:21,qualityStatus:'valid',rankingEligible:true,flags:[]},{id:'m2',path:'demo/B_JV.txt',sample:'DEVICE B',rawSample:'Device_B',group:'B',fw:{eff:18},rv:{eff:19},bestEff:19,qualityStatus:'valid',rankingEligible:true,flags:[]}];e.findings=[{id:'fA',status:'open',severity:'warning',type:'naming',title:'Ambiguous A',target:'m1',measurementId:'m1',evidence:['Device_A alias']}];e.analysis={summary:{measurementCount:2},topNonRef:[],topRef:[],bestBySample:[]};e.design={devices:[{id:'devA',name:'A',sampleNames:['DEVICE A'],solutionIds:[],stack:[],process:{}}],solutions:[]};LF.CanonicalStore.build(e);return e;}
  function install(e,r){LF.DataModel.getExperiment=function(){return e;};LF.State={state:{experiment:e,ui:{route:r||'experiment-understand',selectedMeasurementId:null,selectedDesignDeviceId:'devA'}}};LF.Storage=LF.Storage||{};LF.Storage.getAssistantSettings=function(){return{memoryTurns:4,memoryChars:3000,messageChars:1200,memoryEnabled:true,contextChars:12000};};}
  t['Canonical Store preserves aliases and evidence references']=function(){const e=fake(),s=LF.CanonicalStore.sample(e,'Device_A');assert(s.id,'s1','alias lookup');assert(LF.CanonicalStore.summary(e).relations>0,true,'relations');assert(LF.CanonicalStore.summary(e).evidence>0,true,'evidence');};
  t['assistant starts from a bounded read-only bootstrap context']=function(){const e=fake();install(e,'experiment-results');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,def.steps[0],{userText:'Explain DEVICE A'});assert(built.context.context_pack.profile,'assistant','profile');assert(built.context.tool_policy.mode,'read_only','tool mode');assert(Array.isArray(built.context.tool_observations),true,'observations array');assert(JSON.stringify(built.context).length<12000,true,'bounded');};
  t['assistant final context contains only explicit tool observations']=function(){const e=fake();install(e,'experiment-results');const def=LF.ActionRegistry.action('assistant.chat'),built=LF.ActionContext.build(def,def.steps[0],{userText:'Explain DEVICE A',agentObservations:[{tool:'results.get',arguments:{},result:{summary:{bestSample:'DEVICE A'}}}]});assert(built.context.tools_used,['results.get'],'tool trace');assert(built.context.tool_observations[0].result.summary.bestSample,'DEVICE A','observation');};
  t['ambiguity context contains only requested finding and linked records']=function(){const e=fake();install(e);e.datasetAnalysis={sourceRevision:0,ambiguousFindings:[{id:'fA',measurementId:'m1',title:'Ambiguous A',detail:'',target:'m1'}]};const def=LF.ActionRegistry.action('dataset.resolve-ambiguities'),step=def.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{outputs:{collect:{finding_ids:['fA']}}});assert(built.context.findings.map(function(x){return x.id;}),['fA'],'finding scope');assert(built.context.measurements.map(function(x){return x.id;}),['m1'],'measurement scope');};
  t['Design context contains only selected experiment']=function(){const e=fake();install(e,'experiment-design');e.designAnalysis={sourceRevision:0,samples:[{sample:e.samples[0],unknownFields:['stack']},{sample:e.samples[1],unknownFields:['stack']}],summary:{samples:2}};const def=LF.ActionRegistry.action('design.infer'),step=def.steps.find(function(x){return x.type==='AI';}),built=LF.ActionContext.build(def,step,{params:{deviceId:'devA'}});assert(built.context.scope.sample_names,['DEVICE A'],'single experiment');assert(built.context.scope.unknown_fields,['stack'],'missing only');assert(built.context.design_evidence_summary.knowledge_fallback_available,true,'knowledge fallback available');assert(built.context.domain_knowledge.source,'knowledge.perovskite-design','knowledge source');};
  t['Data Contract is scoped to ambiguity repair, not downstream prose']=function(){const ambiguity=LF.ActionRegistry.action('dataset.resolve-ambiguities'),design=LF.ActionRegistry.action('design.infer'),results=LF.ActionRegistry.action('results.interpret'),report=LF.ActionRegistry.action('report.generate');assert((ambiguity.policies||[]).includes('policy.data-ground-truth'),true,'ambiguity gets contract');assert((design.policies||[]).includes('policy.data-ground-truth'),false,'design uses context pack');assert((results.policies||[]).includes('policy.data-ground-truth'),false,'results uses context pack');assert((report.policies||[]).includes('policy.data-ground-truth'),false,'report uses context pack');};
  t['shared Experiment Brief is present in every AI context base']=function(){const e=fake();install(e,'experiment-results');e.experimentBrief=LF.ExperimentBrief.ensure(e);e.experimentBrief.ai={summary:'Shared scientific brief',inputSignature:LF.ExperimentBrief.signature(e),provenance:'ai_enrichment'};const resultDef=LF.ActionRegistry.action('results.interpret'),resultStep=resultDef.steps.find(function(x){return x.type==='AI';}),result=LF.ActionContext.build(resultDef,resultStep,{});const reportDef=LF.ActionRegistry.action('report.generate'),reportStep=reportDef.steps.find(function(x){return x.type==='AI';}),report=LF.ActionContext.build(reportDef,reportStep,{params:{document_kind:'lab'}});assert(result.context.experiment_brief.status,'ai_enriched','results brief');assert(report.context.experiment_brief.status,'ai_enriched','report brief');assert(report.context.experiment_brief.ai.summary,'Shared scientific brief','shared AI summary');};
  t['scientific Action contexts receive bounded ranked Knowledge Base records']=function(){const e=fake();install(e,'experiment-results'),previous=LF.KnowledgeBase,record={id:'kb_ranked',kind:'material',name:'SnO2',summary:'ETL',tags:['SnO2'],data:{role:'ETL'},sources:[{title:'Paper',doi:'10.1000/kb'}],retrieval:{score:9,matched_terms:['sno2']}};LF.KnowledgeBase={status:function(){return{connected:true};},search:function(){return[record];},context:function(){return[record];}};try{const resultDef=LF.ActionRegistry.action('results.interpret'),resultStep=resultDef.steps.find(function(x){return x.type==='AI';}),result=LF.ActionContext.build(resultDef,resultStep,{});assert(result.context.local_knowledge_base.records[0].id,'kb_ranked','Results retrieval');assert(result.context.local_knowledge_base.records[0].data.role,'ETL','knowledge data retained');const designDef=LF.ActionRegistry.action('design.infer'),designStep=designDef.steps.find(function(x){return x.type==='AI';}),design=LF.ActionContext.build(designDef,designStep,{params:{deviceId:'devA'}});assert(design.context.local_knowledge_base.records[0].id,'kb_ranked','Design retrieval');}finally{LF.KnowledgeBase=previous;}};
  t['dataset Analyze is deterministic and promptless']=function(){const d=LF.ActionRegistry.action('dataset.analyze');assert(d.type,'DETERMINISTIC');assert(LF.ActionRegistry.prompt(d.id),'');};
  return t;
};
