(() => {
  'use strict';
  const init=root=>{
    const S=LabFlowProjectStore,esc=S.esc;let state=S.get('fabrication',{stacks:[]}),editing=null,layers=[],processes=[];
    const form=root.querySelector('[data-stack-editor]');
    const materialNames=()=>[...new Set([...(window.LabFlowCabinet?.list().filter(item=>item.category==='materials').map(item=>item.name)||[]),...(S.get('materials',{resources:[]}).resources||[]).map(item=>item.name)])];
    const row=(layer={},index=0)=>`<div class="layer-editor" data-layer-number="${String(index+1).padStart(2,'0')}"><label><span>Material</span><input class="input" list="stackMaterialOptions" placeholder="Choose or name" value="${esc(layer.material||'')}" data-k="material"></label><label><span>Role</span><input class="input" placeholder="Absorber" value="${esc(layer.role||'')}" data-k="role"></label><label><span>Thickness</span><input class="input" type="number" step="any" placeholder="500" value="${esc(layer.thickness??'')}" data-k="thickness"></label><label><span>Unit</span><select class="input" data-k="unit"><option>nm</option><option>µm</option><option>mm</option></select></label><label><span>Method / source</span><input class="input" placeholder="Spin coating" value="${esc(layer.method||'')}" data-k="method"></label><div class="layer-order"><button class="icon-button small" type="button" data-layer-up aria-label="Move up">↑</button><button class="icon-button small" type="button" data-layer-down aria-label="Move down">↓</button><button class="icon-button small" type="button" data-layer-remove aria-label="Remove">×</button></div></div>`;
    const proc=(item={})=>`<div class="process-editor"><input class="input" placeholder="Spin coating / Annealing" value="${esc(item.name||'')}" data-k="name"><input class="input" placeholder="1500 rpm" value="${esc(item.value||'')}" data-k="value"><input class="input" placeholder="30 s" value="${esc(item.duration||'')}" data-k="duration"><input class="input" placeholder="Notes" value="${esc(item.notes||'')}" data-k="notes"><button class="icon-button small" type="button" data-process-remove>×</button></div>`;
    const sync=()=>{layers=[...form.querySelectorAll('.layer-editor')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-k]')].map(input=>[input.dataset.k,input.value])));processes=[...form.querySelectorAll('.process-editor')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-k]')].map(input=>[input.dataset.k,input.value])))};
    const tone=layer=>/substrate|glass/i.test(`${layer.role} ${layer.material}`)?'substrate':/absorber|perovskite/i.test(`${layer.role} ${layer.material}`)?'absorber':/contact|ito|au|ag/i.test(`${layer.role} ${layer.material}`)?'contact':'transport';
    const editor=()=>{form.querySelector('[data-layer-list]').innerHTML=`<datalist id="stackMaterialOptions">${materialNames().map(name=>`<option value="${esc(name)}"></option>`).join('')}</datalist>`+layers.map((item,index)=>row(item,index)).join('');form.querySelectorAll('.layer-editor').forEach((node,index)=>node.querySelector('[data-k="unit"]').value=layers[index].unit||'nm');form.querySelector('[data-process-list]').innerHTML=processes.map(proc).join('');const max=Math.max(...layers.map(layer=>Number(layer.thickness)||1),1);form.querySelector('[data-layer-visual]').innerHTML=[...layers].reverse().map((layer,index)=>`<div class="stack-band ${tone(layer)}" style="--layer-size:${Math.max(34,Math.min(62,34+(Number(layer.thickness)||1)/max*28))}px"><span class="stack-band-edge"></span><div><small>${esc(layer.role||'Layer')}</small><strong>${esc(layer.material||'Unnamed layer')}</strong></div><span><b>${esc(layer.thickness||'—')}</b> ${esc(layer.unit||'nm')}</span></div>`).join('')||'<div class="stack-empty-layer">Add the substrate to begin</div>'};
    const render=()=>{const overview=root.querySelector('[data-stack-overview]');if(overview){const layerCount=state.stacks.reduce((sum,stack)=>sum+(stack.layers?.length||0),0),sampleCount=state.stacks.reduce((sum,stack)=>sum+(stack.samples?.length||0),0),processCount=state.stacks.reduce((sum,stack)=>sum+(stack.processes?.length||0),0);overview.innerHTML=[[state.stacks.length,'stack variants'],[sampleCount,'sample targets'],[layerCount,'defined layers'],[processCount,'fabrication actions']].map(([value,label])=>`<span><b>${value}</b><small>${label}</small></span>`).join('')}root.querySelector('[data-stack-list]').innerHTML=state.stacks.map(stack=>`<article class="panel record-card stack-record"><div class="stack-record-head"><div><span class="eyebrow">${esc(stack.origin?'Cabinet snapshot':stack.condition||'Project stack')}</span><h4>${esc(stack.name)}</h4></div><span class="pipeline-badge"><i></i>${(stack.samples||[]).length} targets</span></div><div class="stack-record-cross-section">${stack.layers.map(layer=>`<span class="${tone(layer)}"><b>${esc(layer.material)}</b><em>${esc(layer.thickness)} ${esc(layer.unit)}</em></span>`).join('')}</div><div class="stack-record-process">${stack.processes.slice(0,4).map(item=>`<span>${esc(item.name)} · ${esc(item.value||item.duration||'')}</span>`).join('')||'<span>No fabrication actions</span>'}</div><small>${esc(stack.atmosphere||'Atmosphere not set')} · ${esc(stack.instrument||'Instrument not set')}</small><footer><button class="button small" data-edit-stack="${stack.id}">Edit</button><button class="button small" data-duplicate-stack="${stack.id}">Duplicate</button><button class="button small danger" data-remove-stack="${stack.id}">Remove</button></footer></article>`).join('');root.querySelector('[data-stack-empty]').hidden=state.stacks.length>0};
    const open=stack=>{editing=stack?.id||null;form.hidden=false;form.name.value=stack?.name||'';form.condition.value=stack?.condition||'';form.samples.value=(stack?.samples||[]).join(', ');form.atmosphere.value=stack?.atmosphere||'';form.instrument.value=stack?.instrument||'';form.operator.value=stack?.operator||'';form.notes.value=stack?.notes||'';form.saveCabinet.checked=false;layers=structuredClone(stack?.layers||[{material:'Glass / ITO',role:'Substrate',thickness:1.1,unit:'mm',method:'Cleaning'},{material:'SnO₂',role:'Electron transport',thickness:30,unit:'nm',method:'Spin coating'},{material:'Perovskite',role:'Absorber',thickness:500,unit:'nm',method:'Spin coating'}]);processes=structuredClone(stack?.processes||[{name:'Spin coating',value:'1500 rpm',duration:'30 s',notes:''},{name:'Annealing',value:'100 °C',duration:'30 min',notes:''}]);editor();form.scrollIntoView({behavior:'smooth',block:'start'})};
    root.onclick=event=>{const button=event.target.closest('button');if(!button)return;const find=id=>state.stacks.find(stack=>stack.id===id);if(button.matches('[data-stack-new]'))open();if(button.matches('[data-stack-close]'))form.hidden=true;if(button.dataset.editStack)open(find(button.dataset.editStack));if(button.dataset.duplicateStack){const stack=structuredClone(find(button.dataset.duplicateStack));stack.id=S.uid('stack');stack.name+=' copy';stack.origin=null;state.stacks.push(stack);S.set('fabrication',state);render()}if(button.dataset.removeStack){state.stacks=state.stacks.filter(stack=>stack.id!==button.dataset.removeStack);S.set('fabrication',state);render()}if(button.matches('[data-add-layer]')){sync();layers.push({material:'',role:'',thickness:'',unit:'nm',method:''});editor()}if(button.matches('[data-add-process]')){sync();processes.push({});editor()}const layerRow=button.closest('.layer-editor');if(layerRow){sync();const index=[...form.querySelectorAll('.layer-editor')].indexOf(layerRow);if(button.matches('[data-layer-remove]'))layers.splice(index,1);if(button.matches('[data-layer-up]')&&index>0)[layers[index],layers[index-1]]=[layers[index-1],layers[index]];if(button.matches('[data-layer-down]')&&index<layers.length-1)[layers[index],layers[index+1]]=[layers[index+1],layers[index]];editor()}if(button.matches('[data-process-remove]')){sync();processes.splice([...form.querySelectorAll('.process-editor')].indexOf(button.closest('.process-editor')),1);editor()}};
    form.oninput=()=>{sync();const visual=form.querySelector('[data-layer-visual]');if(visual){const max=Math.max(...layers.map(layer=>Number(layer.thickness)||1),1);visual.innerHTML=[...layers].reverse().map(layer=>`<div class="stack-band ${tone(layer)}" style="--layer-size:${Math.max(34,Math.min(62,34+(Number(layer.thickness)||1)/max*28))}px"><span class="stack-band-edge"></span><div><small>${esc(layer.role||'Layer')}</small><strong>${esc(layer.material||'Unnamed layer')}</strong></div><span><b>${esc(layer.thickness||'—')}</b> ${esc(layer.unit||'nm')}</span></div>`).join('')}};
    form.onsubmit=event=>{event.preventDefault();sync();const previous=state.stacks.find(item=>item.id===editing),stack={id:editing||S.uid('stack'),name:form.name.value.trim(),condition:form.condition.value.trim(),samples:form.samples.value.split(',').map(item=>item.trim()).filter(Boolean),layers,processes,atmosphere:form.atmosphere.value.trim(),instrument:form.instrument.value.trim(),operator:form.operator.value.trim(),notes:form.notes.value.trim(),origin:previous?.origin||null,savedAt:new Date().toISOString()};const index=state.stacks.findIndex(item=>item.id===stack.id);index<0?state.stacks.push(stack):state.stacks[index]=stack;S.set('fabrication',state);if(form.saveCabinet.checked&&window.LabFlowCabinet)LabFlowCabinet.save({...stack,id:null,category:'stacks',type:'Stack',role:'Stack template',description:stack.notes||'Reusable device stack.',tags:[stack.name,stack.condition,...stack.layers.map(layer=>layer.material)].filter(Boolean)});form.hidden=true;render()};
    document.addEventListener('labflow:project-data',event=>{state=event.detail.fabrication||state;render()},{once:true});render();
  };
  document.addEventListener('labflow:pipeline-step',event=>{if(event.detail.pipelineId==='chose'&&event.detail.id==='stack')requestAnimationFrame(()=>init(document.getElementById('stackTool')))});
})();
